### ISSUE TITLE
Remove v= parameter tagging of fontawesome URLs

### ISSUE THREAD

**Issue by forrestcavalier** [kerwizzy/ZappWiki#9]
The fontawesome URLs have a query string, which interferes with operation on generic http servers. See background at https://github.com/FortAwesome/Font-Awesome/issues/3286

**Comment by kerwizzy** [comment]
In the latest versions of ZappWiki, (in fact, since 8231ce9, and even before that), page sources are set by the server. Currently, there are no v= tags in FontAwesome URLS. Please update your wiki to get the latest version.
